name: Test API routes for Preview

on: 
  push:
    branches:
      - backend-development

jobs:
  integration-tests-and-deploy:
    name: Run Integration Tests and Deploy for Preview
    environment: Preview
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.6.0'
    
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Install waiton
      run: npm install wait-on --legacy-peer-deps

    - name: Create the .env.local file
      run: |
        touch .env.local
        echo MONGODB_USER=${{ vars.MONGODB_USER }} >> .env.local
        echo MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }} >> .env.local
        echo MONGODB_DB_NAME=${{ vars.MONGODB_DB_NAME }} >> .env.local
        echo MONGODB_DB_PROD=${{ vars.MONGODB_DB_PROD }} >> .env.local
        echo MONGODB_PROJECT_ID=${{ vars.MONGODB_PROJECT_ID }} >> .env.local
        echo MONGODB_PROJECT_PRIVATE_KEY=${{ secrets.MONGODB_PROJECT_PRIVATE_KEY }}  >> .env.local
        echo MONGODB_PROJECT_PUBLIC_KEY=${{ vars.MONGODB_PROJECT_PUBLIC_KEY }}  >> .env.local
        echo AUTH_CLIENT_ID=${{ vars.AUTH_CLIENT_ID }} >> .env.local
        echo AUTH_CLIENT_SECRET=${{ secrets.AUTH_CLIENT_SECRET }} >> .env.local
        echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env.local
        echo EMAIL_SENDER_SERVICE_ACCOUNT_CLIENT_ID=${{ vars.EMAIL_SENDER_SERVICE_ACCOUNT_CLIENT_ID }} >> .env.local
        echo EMAIL_SENDER_SERVICE_ACCOUNT_PRIVATE_KEY=${{ secrets.EMAIL_SENDER_SERVICE_ACCOUNT_PRIVATE_KEY }} >> .env.local
        echo BREVO_API_KEY=${{ secrets.BREVO_API_KEY }} >> .env.local
        echo DEADLINKS_CHECK_EMAIL_PASSWORD=${{ secrets.DEADLINKS_CHECK_EMAIL_PASSWORD }} >> .env.local

    - name: Build and serve the app
      run: npm run prod &

    - name: Wait for the app to start
      run: npx wait-on -t 240000 http://localhost:3000

    - name: Run the integration tests
      id: run-tests # Add an ID so we can reference this step if needed.
      run: npm run test:integration